# Generated by Django 5.0.7 on 2024-07-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_user', '0002_remove_useraccountmodel_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountmodel',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
