# Generated by Django 5.0.7 on 2024-08-04 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transaction', '0002_alter_transactionmodel_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionmodel',
            old_name='ammount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='transactionmodel',
            old_name='balance_after',
            new_name='balance_after_transaction',
        ),
    ]
