# Generated by Django 5.0.7 on 2024-08-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transaction', '0003_rename_ammount_transactionmodel_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='transaction_type',
            field=models.IntegerField(choices=[('D', 'Deposit'), ('W', 'Withdrawal'), ('L', 'Loan'), ('P', 'Loan Paid')]),
        ),
    ]
