# Generated by Django 5.0.7 on 2024-08-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transaction', '0005_alter_transactionmodel_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposite'), (2, 'Withdrawal'), (3, 'Loan'), (4, 'Loan Paid'), (5, 'Transfer Out'), (6, 'Transfer In')], null=True),
        ),
    ]
